import { createFileRoute } from "@tanstack/react-router";
import { ServicePage } from "@/components/service-page";
import { Percent, Receipt, FileSpreadsheet, ShieldCheck, RefreshCcw, MessageSquare } from "lucide-react";

export const Route = createFileRoute("/services/withholding-tax")({
  head: () => ({
    meta: [
      { title: "Withholding Tax Services in Kenya — WHT Filing & Certificates | Assetech" },
      { name: "description", content: "Withholding tax rate determination, monthly iTax filing, automatic WHT certificates and credit reconciliation by Assetech Nakuru." },
      { property: "og:title", content: "Withholding Tax — Assetech" },
      { property: "og:description", content: "WHT deducted, remitted and reconciled on every qualifying payment." },
    ],
  }),
  component: () => (
    <ServicePage
      eyebrow="Tax · WHT"
      title="Withholding tax, deducted and remitted correctly"
      intro="Every professional fee, consultancy payment, rent, interest, dividend and management fee has a WHT rule attached. We apply the right rate, remit on iTax and issue certificates automatically."
      theme={{
        heroGradient: "linear-gradient(135deg, oklch(0.22 0.05 235) 0%, oklch(0.36 0.10 232) 60%, oklch(0.60 0.17 228) 100%)",
        iconBg: "bg-sky-500/10 text-sky-600",
        numberBg: "bg-sky-600 text-white",
        checkColor: "text-sky-600",
      }}
      overview={{
        heading: "How withholding tax works",
        paragraphs: [
          "Withholding Tax is tax deducted at source by the payer on specified payments to another party. The payer holds the tax and remits it to KRA on the payee's behalf, then issues a certificate the payee uses as a credit against their own income tax.",
          "Rates depend on the nature of the payment and the residence of the payee. Common rates: professional and management fees 5% (resident) / 20% (non-resident); consultancy 5% / 20%; rent to residents 10%; dividends 5% / 15%; interest 15%; royalties 5% / 20%; contractual services 3% / 20%.",
          "WHT must be remitted on iTax by the 20th of the following month. Once payment is made, iTax auto-generates the WHT certificate and emails it to the payee — provided the correct KRA PIN was captured. Errors in PIN or amount create disputes that are painful to unwind later.",
          "We identify which of your payments are withholdable, apply the correct rate, remit monthly on iTax, issue certificates and reconcile WHT credits against your own income tax return.",
        ],
      }}
      whyImportant={[
        { title: "Payer is on the hook", desc: "If you fail to withhold, KRA collects the tax from you, not the payee. That converts a 5% obligation into a 100% cost." },
        { title: "Wrong rate = penalties", desc: "Under-deducting on a non-resident payment (20% treated as 5%) creates a 15% shortfall plus penalties and interest against you." },
        { title: "Payees demand certificates", desc: "Consultants, landlords and contractors need WHT certificates to claim credit on their own returns — poor practice damages relationships." },
        { title: "WHT credits reduce your tax", desc: "As a payee, unclaimed WHT credits are lost tax already paid. We track and offset every certificate against your annual return." },
        { title: "Non-resident traps", desc: "Cross-border consultancy, software licences and management fees have different rates, DTA overrides and reporting rules that are easy to miss." },
        { title: "Audit target", desc: "WHT compliance is one of KRA's favourite audit areas — expense schedules are cross-checked against WHT filings." },
      ]}
      includes={[
        { icon: Percent, title: "Rate Determination", desc: "Correct WHT rate for every payment type — resident and non-resident — including DTA analysis." },
        { icon: Receipt, title: "Monthly Remittance", desc: "WHT filed on iTax and payment slip generated by the 20th." },
        { icon: FileSpreadsheet, title: "Certificate Issuance", desc: "Auto-generated certificates verified, tracked and shared with your payees." },
        { icon: ShieldCheck, title: "Credit Reconciliation", desc: "Every certificate you receive as a payee reconciled and applied against your income tax." },
        { icon: RefreshCcw, title: "Back-filing", desc: "Reconstruction and remittance of missed WHT months, with waiver applications." },
        { icon: MessageSquare, title: "KRA Support", desc: "Response to WHT-specific assessments, PIN mismatches and objections." },
      ]}
      process={[
        { title: "Map", desc: "Review your payment types and identify all withholdable transactions." },
        { title: "Deduct", desc: "Apply correct rates at the point of payment; net to payee, WHT held." },
        { title: "Remit", desc: "iTax filing and payment by the 20th; certificates issued." },
        { title: "Reconcile", desc: "Match against expense ledgers and offset your own credits at year end." },
      ]}
      whyAssetech={[
        { title: "Cross-border expertise", desc: "We handle non-resident WHT, double taxation agreement analysis, and Kenya's specific rules on digital service payments." },
        { title: "Registered tax agents", desc: "We can lodge, correct and defend your WHT filings under our agent credentials with KRA." },
        { title: "Certificate hygiene", desc: "We chase, verify and file every certificate — no more lost credits at year-end." },
        { title: "Integrated with accounts", desc: "When we do your bookkeeping too, WHT is deducted at the point the invoice is entered — never forgotten later." },
        { title: "DTA-aware", desc: "We apply the right treaty rate (Kenya has DTAs with UK, India, Canada, France, Germany, South Africa, UAE and more) so you never over-deduct." },
        { title: "Fixed monthly fee", desc: "WHT is bundled with your tax retainer, not billed as an extra." },
      ]}
      audience={[
        "Companies making regular consultancy and professional payments",
        "Landlords with WHT-eligible tenants",
        "Businesses paying non-resident suppliers",
        "Consultants and professionals reclaiming WHT credits",
        "Property managers handling tenant WHT",
      ]}
      faqs={[
        { q: "Do I withhold on all consultant payments?", a: "Yes for management, professional and consultancy fees to residents (5%) and non-residents (20%), subject to DTAs. We apply the right rate case by case." },
        { q: "The payee refuses the deduction. What do I do?", a: "The law is with you as the payer. Deduct, remit and issue the certificate — the payee claims credit on their return." },
        { q: "I forgot to deduct on a large invoice. Options?", a: "Voluntary disclosure, remit now, and either recover from the payee or absorb it. We help you scope the cheapest legal route." },
        { q: "Can I claim WHT credits from prior years?", a: "Yes, within the statute of limitations — usually five years. We rebuild the schedule and amend returns where beneficial." },
      ]}
    />
  ),
});