import { createFileRoute } from "@tanstack/react-router";
import { ServicePage } from "@/components/service-page";
import { Users, FileSpreadsheet, Receipt, ShieldCheck, RefreshCcw, MessageSquare } from "lucide-react";

export const Route = createFileRoute("/services/paye")({
  head: () => ({
    meta: [
      { title: "PAYE, NSSF, SHIF, Housing Levy & NITA — Payroll Compliance | Assetech" },
      { name: "description", content: "End-to-end payroll compliance in Kenya — PAYE, NSSF, SHIF, Affordable Housing Levy and NITA. Monthly processing, remittance and P9 certificates by Assetech Nakuru." },
      { property: "og:title", content: "PAYE & Statutory Deductions — Assetech" },
      { property: "og:description", content: "Payroll, PAYE, NSSF, SHIF, AHL and NITA — filed accurately every month." },
    ],
  }),
  component: () => (
    <ServicePage
      eyebrow="Tax · Payroll & Statutory"
      title="Payroll compliance without the monthly stress"
      intro="PAYE, NSSF, SHIF, Affordable Housing Levy and NITA — computed, deducted, remitted and reported so your team is paid correctly and KRA never has to chase."
      theme={{
        heroGradient: "linear-gradient(135deg, oklch(0.22 0.05 235) 0%, oklch(0.36 0.10 232) 60%, oklch(0.60 0.17 228) 100%)",
        iconBg: "bg-sky-500/10 text-sky-600",
        numberBg: "bg-sky-600 text-white",
        checkColor: "text-sky-600",
      }}
      overview={{
        heading: "The Kenyan payroll stack, explained",
        paragraphs: [
          "Every employer in Kenya operates a payroll subject to five statutory deductions. PAYE is deducted at graduated rates from 10% on the first KES 24,000 up to 35% on income above KES 800,000 per month, less personal relief and qualifying deductions like mortgage interest and pension.",
          "NSSF contributions moved to a tiered structure under the NSSF Act 2013, with employer and employee each contributing 6% of pensionable pay up to the upper limit. SHIF (Social Health Insurance Fund) replaced NHIF in 2024 and is deducted at 2.75% of gross salary, with a KES 300 minimum. The Affordable Housing Levy is 1.5% deducted from the employee and 1.5% matched by the employer. NITA is a flat KES 50 per employee per month.",
          "All five deductions are remitted by the 9th day of the following month — PAYE and Housing Levy on iTax, NSSF on the NSSF portal, SHIF on the SHA portal, NITA on the NITA portal. Every employee must receive a P9 certificate at year end for their own tax return.",
          "We run your monthly payroll, issue payslips, remit every deduction on the correct portal, keep your payroll register, and produce P9 certificates and audit-ready files at year end.",
        ],
      }}
      whyImportant={[
        { title: "25% late-payment penalty on PAYE", desc: "PAYE carries the harshest late-payment penalty in the Tax Procedures Act — 25% of the tax due — plus 1% monthly interest." },
        { title: "Directors are personally liable", desc: "Unpaid PAYE can be pursued against directors personally under the Tax Procedures Act. Payroll arrears are not just a company problem." },
        { title: "Staff trust and retention", desc: "Wrong payslips, missing NSSF or SHIF contributions and lost P9s destroy trust with your team faster than almost anything else." },
        { title: "Audit and grant compliance", desc: "Donors, lenders and external auditors scrutinise payroll first. Clean statutory files remove the biggest audit risk in most SMEs." },
        { title: "Wrong deductions are personal cost", desc: "Under-deducting PAYE from an employee usually cannot be recovered later — the shortfall lands on the employer." },
        { title: "Cross-portal complexity", desc: "iTax, NSSF, SHA and NITA each want their own submission every month. One missed portal is a full compliance breach." },
      ]}
      includes={[
        { icon: Users, title: "Monthly Payroll", desc: "Gross-to-net computation, payslips and payroll register for every pay cycle." },
        { icon: Receipt, title: "PAYE Remittance", desc: "P10 return filed on iTax and payment slip generated by the 9th." },
        { icon: FileSpreadsheet, title: "NSSF, SHIF, AHL & NITA", desc: "Remittance on each portal with confirmation captured to your compliance file." },
        { icon: ShieldCheck, title: "P9 Certificates", desc: "Year-end P9s for every employee, ready for their personal returns." },
        { icon: RefreshCcw, title: "Payroll Health Check", desc: "Diagnostic review of past payrolls to close exposures before audit." },
        { icon: MessageSquare, title: "KRA & SHA Support", desc: "Response to notices, reconciliations and back-filing where required." },
      ]}
      process={[
        { title: "Onboard", desc: "Employee data, contracts, reliefs and prior payrolls captured." },
        { title: "Process", desc: "Monthly payroll run, review with you, payslips distributed." },
        { title: "Remit", desc: "PAYE, NSSF, SHIF, AHL and NITA lodged on their respective portals." },
        { title: "Report", desc: "Monthly compliance pack and year-end P9s delivered." },
      ]}
      whyAssetech={[
        { title: "All five deductions, one team", desc: "You are not juggling a payroll bureau, a tax consultant and separate portals — we handle the full stack." },
        { title: "Backfilling experience", desc: "We have cleared 12+ month PAYE backlogs, reconciled with KRA and lodged waiver applications." },
        { title: "Confidential handling", desc: "Payroll data is treated with strict access controls — salaries never circulate outside the engagement team." },
        { title: "Onsite in Nakuru", desc: "For clients who prefer in-person handover of payslips and cash, our team can be onsite each pay day." },
        { title: "Audit-ready files", desc: "Every month closes with a documented pack that satisfies external auditors and donors first time." },
        { title: "Fixed fee per employee", desc: "Simple, predictable per-headcount pricing — no surprises when you add or lose staff." },
      ]}
      audience={[
        "SMEs with 3–200 employees",
        "NGOs and donor-funded projects",
        "Schools, hospitals and SACCOs",
        "Hospitality groups with shift-based payroll",
        "Businesses with PAYE arrears or KRA notices",
        "Startups formalising their first payroll",
      ]}
      faqs={[
        { q: "Can you take over payroll mid-year?", a: "Yes. We capture year-to-date figures from your existing payslips or system, reconcile with iTax, and take over from the next cycle." },
        { q: "Do you handle casual and contract workers?", a: "Yes. Casuals have their own PAYE treatment (30% flat over the daily threshold) and we track WHT for consultants and contractors." },
        { q: "What if we have unremitted PAYE from prior months?", a: "We quantify the exposure, prepare returns, generate payment slips and where the reasons qualify we lodge waiver applications for penalties." },
        { q: "Do you provide payslips to staff directly?", a: "Yes — via secure email or a printed pack delivered to your office, whichever you prefer." },
      ]}
    />
  ),
});