/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesWithholdingTaxRouteImport } from './routes/services.withholding-tax'
import { Route as ServicesVatRouteImport } from './routes/services.vat'
import { Route as ServicesTotRouteImport } from './routes/services.tot'
import { Route as ServicesTaxRouteImport } from './routes/services.tax'
import { Route as ServicesRentalIncomeTaxRouteImport } from './routes/services.rental-income-tax'
import { Route as ServicesPayeRouteImport } from './routes/services.paye'
import { Route as ServicesIncomeTaxRouteImport } from './routes/services.income-tax'
import { Route as ServicesFixedAssetManagementRouteImport } from './routes/services.fixed-asset-management'
import { Route as ServicesExciseDutyRouteImport } from './routes/services.excise-duty'
import { Route as ServicesEtimsFilingRouteImport } from './routes/services.etims-filing'
import { Route as ServicesCapitalGainsTaxRouteImport } from './routes/services.capital-gains-tax'
import { Route as ServicesBusinessConsultancyRouteImport } from './routes/services.business-consultancy'
import { Route as ServicesAuditAssuranceRouteImport } from './routes/services.audit-assurance'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWithholdingTaxRoute = ServicesWithholdingTaxRouteImport.update({
  id: '/services/withholding-tax',
  path: '/services/withholding-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVatRoute = ServicesVatRouteImport.update({
  id: '/services/vat',
  path: '/services/vat',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTotRoute = ServicesTotRouteImport.update({
  id: '/services/tot',
  path: '/services/tot',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTaxRoute = ServicesTaxRouteImport.update({
  id: '/services/tax',
  path: '/services/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRentalIncomeTaxRoute = ServicesRentalIncomeTaxRouteImport.update({
  id: '/services/rental-income-tax',
  path: '/services/rental-income-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPayeRoute = ServicesPayeRouteImport.update({
  id: '/services/paye',
  path: '/services/paye',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIncomeTaxRoute = ServicesIncomeTaxRouteImport.update({
  id: '/services/income-tax',
  path: '/services/income-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFixedAssetManagementRoute =
  ServicesFixedAssetManagementRouteImport.update({
    id: '/services/fixed-asset-management',
    path: '/services/fixed-asset-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesExciseDutyRoute = ServicesExciseDutyRouteImport.update({
  id: '/services/excise-duty',
  path: '/services/excise-duty',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEtimsFilingRoute = ServicesEtimsFilingRouteImport.update({
  id: '/services/etims-filing',
  path: '/services/etims-filing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCapitalGainsTaxRoute = ServicesCapitalGainsTaxRouteImport.update({
  id: '/services/capital-gains-tax',
  path: '/services/capital-gains-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBusinessConsultancyRoute =
  ServicesBusinessConsultancyRouteImport.update({
    id: '/services/business-consultancy',
    path: '/services/business-consultancy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAuditAssuranceRoute = ServicesAuditAssuranceRouteImport.update({
  id: '/services/audit-assurance',
  path: '/services/audit-assurance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/audit-assurance': typeof ServicesAuditAssuranceRoute
  '/services/business-consultancy': typeof ServicesBusinessConsultancyRoute
  '/services/capital-gains-tax': typeof ServicesCapitalGainsTaxRoute
  '/services/etims-filing': typeof ServicesEtimsFilingRoute
  '/services/excise-duty': typeof ServicesExciseDutyRoute
  '/services/fixed-asset-management': typeof ServicesFixedAssetManagementRoute
  '/services/income-tax': typeof ServicesIncomeTaxRoute
  '/services/paye': typeof ServicesPayeRoute
  '/services/rental-income-tax': typeof ServicesRentalIncomeTaxRoute
  '/services/tax': typeof ServicesTaxRoute
  '/services/tot': typeof ServicesTotRoute
  '/services/vat': typeof ServicesVatRoute
  '/services/withholding-tax': typeof ServicesWithholdingTaxRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/audit-assurance': typeof ServicesAuditAssuranceRoute
  '/services/business-consultancy': typeof ServicesBusinessConsultancyRoute
  '/services/capital-gains-tax': typeof ServicesCapitalGainsTaxRoute
  '/services/etims-filing': typeof ServicesEtimsFilingRoute
  '/services/excise-duty': typeof ServicesExciseDutyRoute
  '/services/fixed-asset-management': typeof ServicesFixedAssetManagementRoute
  '/services/income-tax': typeof ServicesIncomeTaxRoute
  '/services/paye': typeof ServicesPayeRoute
  '/services/rental-income-tax': typeof ServicesRentalIncomeTaxRoute
  '/services/tax': typeof ServicesTaxRoute
  '/services/tot': typeof ServicesTotRoute
  '/services/vat': typeof ServicesVatRoute
  '/services/withholding-tax': typeof ServicesWithholdingTaxRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/audit-assurance': typeof ServicesAuditAssuranceRoute
  '/services/business-consultancy': typeof ServicesBusinessConsultancyRoute
  '/services/capital-gains-tax': typeof ServicesCapitalGainsTaxRoute
  '/services/etims-filing': typeof ServicesEtimsFilingRoute
  '/services/excise-duty': typeof ServicesExciseDutyRoute
  '/services/fixed-asset-management': typeof ServicesFixedAssetManagementRoute
  '/services/income-tax': typeof ServicesIncomeTaxRoute
  '/services/paye': typeof ServicesPayeRoute
  '/services/rental-income-tax': typeof ServicesRentalIncomeTaxRoute
  '/services/tax': typeof ServicesTaxRoute
  '/services/tot': typeof ServicesTotRoute
  '/services/vat': typeof ServicesVatRoute
  '/services/withholding-tax': typeof ServicesWithholdingTaxRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/services/audit-assurance'
    | '/services/business-consultancy'
    | '/services/capital-gains-tax'
    | '/services/etims-filing'
    | '/services/excise-duty'
    | '/services/fixed-asset-management'
    | '/services/income-tax'
    | '/services/paye'
    | '/services/rental-income-tax'
    | '/services/tax'
    | '/services/tot'
    | '/services/vat'
    | '/services/withholding-tax'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/services/audit-assurance'
    | '/services/business-consultancy'
    | '/services/capital-gains-tax'
    | '/services/etims-filing'
    | '/services/excise-duty'
    | '/services/fixed-asset-management'
    | '/services/income-tax'
    | '/services/paye'
    | '/services/rental-income-tax'
    | '/services/tax'
    | '/services/tot'
    | '/services/vat'
    | '/services/withholding-tax'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/services/audit-assurance'
    | '/services/business-consultancy'
    | '/services/capital-gains-tax'
    | '/services/etims-filing'
    | '/services/excise-duty'
    | '/services/fixed-asset-management'
    | '/services/income-tax'
    | '/services/paye'
    | '/services/rental-income-tax'
    | '/services/tax'
    | '/services/tot'
    | '/services/vat'
    | '/services/withholding-tax'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesAuditAssuranceRoute: typeof ServicesAuditAssuranceRoute
  ServicesBusinessConsultancyRoute: typeof ServicesBusinessConsultancyRoute
  ServicesCapitalGainsTaxRoute: typeof ServicesCapitalGainsTaxRoute
  ServicesEtimsFilingRoute: typeof ServicesEtimsFilingRoute
  ServicesExciseDutyRoute: typeof ServicesExciseDutyRoute
  ServicesFixedAssetManagementRoute: typeof ServicesFixedAssetManagementRoute
  ServicesIncomeTaxRoute: typeof ServicesIncomeTaxRoute
  ServicesPayeRoute: typeof ServicesPayeRoute
  ServicesRentalIncomeTaxRoute: typeof ServicesRentalIncomeTaxRoute
  ServicesTaxRoute: typeof ServicesTaxRoute
  ServicesTotRoute: typeof ServicesTotRoute
  ServicesVatRoute: typeof ServicesVatRoute
  ServicesWithholdingTaxRoute: typeof ServicesWithholdingTaxRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/withholding-tax': {
      id: '/services/withholding-tax'
      path: '/services/withholding-tax'
      fullPath: '/services/withholding-tax'
      preLoaderRoute: typeof ServicesWithholdingTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/vat': {
      id: '/services/vat'
      path: '/services/vat'
      fullPath: '/services/vat'
      preLoaderRoute: typeof ServicesVatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/tot': {
      id: '/services/tot'
      path: '/services/tot'
      fullPath: '/services/tot'
      preLoaderRoute: typeof ServicesTotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/tax': {
      id: '/services/tax'
      path: '/services/tax'
      fullPath: '/services/tax'
      preLoaderRoute: typeof ServicesTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/rental-income-tax': {
      id: '/services/rental-income-tax'
      path: '/services/rental-income-tax'
      fullPath: '/services/rental-income-tax'
      preLoaderRoute: typeof ServicesRentalIncomeTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/paye': {
      id: '/services/paye'
      path: '/services/paye'
      fullPath: '/services/paye'
      preLoaderRoute: typeof ServicesPayeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/income-tax': {
      id: '/services/income-tax'
      path: '/services/income-tax'
      fullPath: '/services/income-tax'
      preLoaderRoute: typeof ServicesIncomeTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/fixed-asset-management': {
      id: '/services/fixed-asset-management'
      path: '/services/fixed-asset-management'
      fullPath: '/services/fixed-asset-management'
      preLoaderRoute: typeof ServicesFixedAssetManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/excise-duty': {
      id: '/services/excise-duty'
      path: '/services/excise-duty'
      fullPath: '/services/excise-duty'
      preLoaderRoute: typeof ServicesExciseDutyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/etims-filing': {
      id: '/services/etims-filing'
      path: '/services/etims-filing'
      fullPath: '/services/etims-filing'
      preLoaderRoute: typeof ServicesEtimsFilingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/capital-gains-tax': {
      id: '/services/capital-gains-tax'
      path: '/services/capital-gains-tax'
      fullPath: '/services/capital-gains-tax'
      preLoaderRoute: typeof ServicesCapitalGainsTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business-consultancy': {
      id: '/services/business-consultancy'
      path: '/services/business-consultancy'
      fullPath: '/services/business-consultancy'
      preLoaderRoute: typeof ServicesBusinessConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/audit-assurance': {
      id: '/services/audit-assurance'
      path: '/services/audit-assurance'
      fullPath: '/services/audit-assurance'
      preLoaderRoute: typeof ServicesAuditAssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesAuditAssuranceRoute: ServicesAuditAssuranceRoute,
  ServicesBusinessConsultancyRoute: ServicesBusinessConsultancyRoute,
  ServicesCapitalGainsTaxRoute: ServicesCapitalGainsTaxRoute,
  ServicesEtimsFilingRoute: ServicesEtimsFilingRoute,
  ServicesExciseDutyRoute: ServicesExciseDutyRoute,
  ServicesFixedAssetManagementRoute: ServicesFixedAssetManagementRoute,
  ServicesIncomeTaxRoute: ServicesIncomeTaxRoute,
  ServicesPayeRoute: ServicesPayeRoute,
  ServicesRentalIncomeTaxRoute: ServicesRentalIncomeTaxRoute,
  ServicesTaxRoute: ServicesTaxRoute,
  ServicesTotRoute: ServicesTotRoute,
  ServicesVatRoute: ServicesVatRoute,
  ServicesWithholdingTaxRoute: ServicesWithholdingTaxRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
