/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesTaxRouteImport } from './routes/services.tax'
import { Route as ServicesFixedAssetManagementRouteImport } from './routes/services.fixed-asset-management'
import { Route as ServicesEtimsFilingRouteImport } from './routes/services.etims-filing'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTaxRoute = ServicesTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFixedAssetManagementRoute =
  ServicesFixedAssetManagementRouteImport.update({
    id: '/fixed-asset-management',
    path: '/fixed-asset-management',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesEtimsFilingRoute = ServicesEtimsFilingRouteImport.update({
  id: '/etims-filing',
  path: '/etims-filing',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/etims-filing': typeof ServicesEtimsFilingRoute
  '/services/fixed-asset-management': typeof ServicesFixedAssetManagementRoute
  '/services/tax': typeof ServicesTaxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/etims-filing': typeof ServicesEtimsFilingRoute
  '/services/fixed-asset-management': typeof ServicesFixedAssetManagementRoute
  '/services/tax': typeof ServicesTaxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/etims-filing': typeof ServicesEtimsFilingRoute
  '/services/fixed-asset-management': typeof ServicesFixedAssetManagementRoute
  '/services/tax': typeof ServicesTaxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/services/etims-filing'
    | '/services/fixed-asset-management'
    | '/services/tax'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/services/etims-filing'
    | '/services/fixed-asset-management'
    | '/services/tax'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/services/etims-filing'
    | '/services/fixed-asset-management'
    | '/services/tax'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/tax': {
      id: '/services/tax'
      path: '/tax'
      fullPath: '/services/tax'
      preLoaderRoute: typeof ServicesTaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/fixed-asset-management': {
      id: '/services/fixed-asset-management'
      path: '/fixed-asset-management'
      fullPath: '/services/fixed-asset-management'
      preLoaderRoute: typeof ServicesFixedAssetManagementRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/etims-filing': {
      id: '/services/etims-filing'
      path: '/etims-filing'
      fullPath: '/services/etims-filing'
      preLoaderRoute: typeof ServicesEtimsFilingRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesEtimsFilingRoute: typeof ServicesEtimsFilingRoute
  ServicesFixedAssetManagementRoute: typeof ServicesFixedAssetManagementRoute
  ServicesTaxRoute: typeof ServicesTaxRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesEtimsFilingRoute: ServicesEtimsFilingRoute,
  ServicesFixedAssetManagementRoute: ServicesFixedAssetManagementRoute,
  ServicesTaxRoute: ServicesTaxRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
