/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWithholdingTaxRouteImport } from './routes/services.withholding-tax'
import { Route as ServicesVatRouteImport } from './routes/services.vat'
import { Route as ServicesTotRouteImport } from './routes/services.tot'
import { Route as ServicesTaxRouteImport } from './routes/services.tax'
import { Route as ServicesRentalIncomeTaxRouteImport } from './routes/services.rental-income-tax'
import { Route as ServicesPayeRouteImport } from './routes/services.paye'
import { Route as ServicesIncomeTaxRouteImport } from './routes/services.income-tax'
import { Route as ServicesFixedAssetManagementRouteImport } from './routes/services.fixed-asset-management'
import { Route as ServicesExciseDutyRouteImport } from './routes/services.excise-duty'
import { Route as ServicesEtimsFilingRouteImport } from './routes/services.etims-filing'
import { Route as ServicesCapitalGainsTaxRouteImport } from './routes/services.capital-gains-tax'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWithholdingTaxRoute = ServicesWithholdingTaxRouteImport.update({
  id: '/withholding-tax',
  path: '/withholding-tax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesVatRoute = ServicesVatRouteImport.update({
  id: '/vat',
  path: '/vat',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTotRoute = ServicesTotRouteImport.update({
  id: '/tot',
  path: '/tot',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTaxRoute = ServicesTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRentalIncomeTaxRoute = ServicesRentalIncomeTaxRouteImport.update({
  id: '/rental-income-tax',
  path: '/rental-income-tax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPayeRoute = ServicesPayeRouteImport.update({
  id: '/paye',
  path: '/paye',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesIncomeTaxRoute = ServicesIncomeTaxRouteImport.update({
  id: '/income-tax',
  path: '/income-tax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFixedAssetManagementRoute =
  ServicesFixedAssetManagementRouteImport.update({
    id: '/fixed-asset-management',
    path: '/fixed-asset-management',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesExciseDutyRoute = ServicesExciseDutyRouteImport.update({
  id: '/excise-duty',
  path: '/excise-duty',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEtimsFilingRoute = ServicesEtimsFilingRouteImport.update({
  id: '/etims-filing',
  path: '/etims-filing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCapitalGainsTaxRoute = ServicesCapitalGainsTaxRouteImport.update({
  id: '/capital-gains-tax',
  path: '/capital-gains-tax',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/capital-gains-tax': typeof ServicesCapitalGainsTaxRoute
  '/services/etims-filing': typeof ServicesEtimsFilingRoute
  '/services/excise-duty': typeof ServicesExciseDutyRoute
  '/services/fixed-asset-management': typeof ServicesFixedAssetManagementRoute
  '/services/income-tax': typeof ServicesIncomeTaxRoute
  '/services/paye': typeof ServicesPayeRoute
  '/services/rental-income-tax': typeof ServicesRentalIncomeTaxRoute
  '/services/tax': typeof ServicesTaxRoute
  '/services/tot': typeof ServicesTotRoute
  '/services/vat': typeof ServicesVatRoute
  '/services/withholding-tax': typeof ServicesWithholdingTaxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/capital-gains-tax': typeof ServicesCapitalGainsTaxRoute
  '/services/etims-filing': typeof ServicesEtimsFilingRoute
  '/services/excise-duty': typeof ServicesExciseDutyRoute
  '/services/fixed-asset-management': typeof ServicesFixedAssetManagementRoute
  '/services/income-tax': typeof ServicesIncomeTaxRoute
  '/services/paye': typeof ServicesPayeRoute
  '/services/rental-income-tax': typeof ServicesRentalIncomeTaxRoute
  '/services/tax': typeof ServicesTaxRoute
  '/services/tot': typeof ServicesTotRoute
  '/services/vat': typeof ServicesVatRoute
  '/services/withholding-tax': typeof ServicesWithholdingTaxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/capital-gains-tax': typeof ServicesCapitalGainsTaxRoute
  '/services/etims-filing': typeof ServicesEtimsFilingRoute
  '/services/excise-duty': typeof ServicesExciseDutyRoute
  '/services/fixed-asset-management': typeof ServicesFixedAssetManagementRoute
  '/services/income-tax': typeof ServicesIncomeTaxRoute
  '/services/paye': typeof ServicesPayeRoute
  '/services/rental-income-tax': typeof ServicesRentalIncomeTaxRoute
  '/services/tax': typeof ServicesTaxRoute
  '/services/tot': typeof ServicesTotRoute
  '/services/vat': typeof ServicesVatRoute
  '/services/withholding-tax': typeof ServicesWithholdingTaxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/services/capital-gains-tax'
    | '/services/etims-filing'
    | '/services/excise-duty'
    | '/services/fixed-asset-management'
    | '/services/income-tax'
    | '/services/paye'
    | '/services/rental-income-tax'
    | '/services/tax'
    | '/services/tot'
    | '/services/vat'
    | '/services/withholding-tax'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/services/capital-gains-tax'
    | '/services/etims-filing'
    | '/services/excise-duty'
    | '/services/fixed-asset-management'
    | '/services/income-tax'
    | '/services/paye'
    | '/services/rental-income-tax'
    | '/services/tax'
    | '/services/tot'
    | '/services/vat'
    | '/services/withholding-tax'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/services/capital-gains-tax'
    | '/services/etims-filing'
    | '/services/excise-duty'
    | '/services/fixed-asset-management'
    | '/services/income-tax'
    | '/services/paye'
    | '/services/rental-income-tax'
    | '/services/tax'
    | '/services/tot'
    | '/services/vat'
    | '/services/withholding-tax'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/withholding-tax': {
      id: '/services/withholding-tax'
      path: '/withholding-tax'
      fullPath: '/services/withholding-tax'
      preLoaderRoute: typeof ServicesWithholdingTaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/vat': {
      id: '/services/vat'
      path: '/vat'
      fullPath: '/services/vat'
      preLoaderRoute: typeof ServicesVatRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/tot': {
      id: '/services/tot'
      path: '/tot'
      fullPath: '/services/tot'
      preLoaderRoute: typeof ServicesTotRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/tax': {
      id: '/services/tax'
      path: '/tax'
      fullPath: '/services/tax'
      preLoaderRoute: typeof ServicesTaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/rental-income-tax': {
      id: '/services/rental-income-tax'
      path: '/rental-income-tax'
      fullPath: '/services/rental-income-tax'
      preLoaderRoute: typeof ServicesRentalIncomeTaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/paye': {
      id: '/services/paye'
      path: '/paye'
      fullPath: '/services/paye'
      preLoaderRoute: typeof ServicesPayeRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/income-tax': {
      id: '/services/income-tax'
      path: '/income-tax'
      fullPath: '/services/income-tax'
      preLoaderRoute: typeof ServicesIncomeTaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/fixed-asset-management': {
      id: '/services/fixed-asset-management'
      path: '/fixed-asset-management'
      fullPath: '/services/fixed-asset-management'
      preLoaderRoute: typeof ServicesFixedAssetManagementRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/excise-duty': {
      id: '/services/excise-duty'
      path: '/excise-duty'
      fullPath: '/services/excise-duty'
      preLoaderRoute: typeof ServicesExciseDutyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/etims-filing': {
      id: '/services/etims-filing'
      path: '/etims-filing'
      fullPath: '/services/etims-filing'
      preLoaderRoute: typeof ServicesEtimsFilingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/capital-gains-tax': {
      id: '/services/capital-gains-tax'
      path: '/capital-gains-tax'
      fullPath: '/services/capital-gains-tax'
      preLoaderRoute: typeof ServicesCapitalGainsTaxRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCapitalGainsTaxRoute: typeof ServicesCapitalGainsTaxRoute
  ServicesEtimsFilingRoute: typeof ServicesEtimsFilingRoute
  ServicesExciseDutyRoute: typeof ServicesExciseDutyRoute
  ServicesFixedAssetManagementRoute: typeof ServicesFixedAssetManagementRoute
  ServicesIncomeTaxRoute: typeof ServicesIncomeTaxRoute
  ServicesPayeRoute: typeof ServicesPayeRoute
  ServicesRentalIncomeTaxRoute: typeof ServicesRentalIncomeTaxRoute
  ServicesTaxRoute: typeof ServicesTaxRoute
  ServicesTotRoute: typeof ServicesTotRoute
  ServicesVatRoute: typeof ServicesVatRoute
  ServicesWithholdingTaxRoute: typeof ServicesWithholdingTaxRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCapitalGainsTaxRoute: ServicesCapitalGainsTaxRoute,
  ServicesEtimsFilingRoute: ServicesEtimsFilingRoute,
  ServicesExciseDutyRoute: ServicesExciseDutyRoute,
  ServicesFixedAssetManagementRoute: ServicesFixedAssetManagementRoute,
  ServicesIncomeTaxRoute: ServicesIncomeTaxRoute,
  ServicesPayeRoute: ServicesPayeRoute,
  ServicesRentalIncomeTaxRoute: ServicesRentalIncomeTaxRoute,
  ServicesTaxRoute: ServicesTaxRoute,
  ServicesTotRoute: ServicesTotRoute,
  ServicesVatRoute: ServicesVatRoute,
  ServicesWithholdingTaxRoute: ServicesWithholdingTaxRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
